name: Web UI automation test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test/docker-build  

jobs:
  build:
    name: Maven Workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Install Google Chrome
      run: |-
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
          GINTAA_EMAIL_ID: ${{ secrets.GINTAA_EMAIL_ID }}
          GINTAA_PASSWORD: ${{ secrets.GINTAA_PASSWORD }}
      run: |-
        echo "${{ secrets.AUTH_TEST }}" > ./src/main/resources/application.properties
        mvn clean install
